---
spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/meeting_booking
    username: meeting_booking
    password: passwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    open-in-view: false
    show-sql: true

  liquibase:
    change-log: 'classpath:db/db.changelog-master.xml'

  jackson:
    default-property-inclusion: non_null
  mvc:
    throw-exception-if-no-handler-found: true

logging:
  level:
    meeting.booking.server: INFO
server:
  error:
    whitelabel:
      enabled: true
---
spring:
  profiles: dev

logging:
  file: logs/dev_app.log
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
#    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    meeting.booking.server: DEBUG

  # Templates reloading during development
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false

  # Static resources reloading during development
  resources:
    static-locations: file:src/main/resources/static/
    cache:
      period: 0s

---

spring:
  profiles: prod

logging:
  file: logs/prod_app.log
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: WARN
    meeting.booking.server: INFO
---